name: restart_app_example
description: Demonstrates how to use the restart plugin.

publish_to: 'none'

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  restart_app:
    path: ../



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true